//Find out all the subsequnece of string and print them.
// what is subsequence : a String is a subsequence of a given steing, that is generated by deleting some character of a given string without changing its order

/* Approach 
To solve the problem iterating through each character of the input string, and  two recursive calls  is madee at each position: one to include the character in the substring being generated, and another to exclude it. The base case of the recursion occurs when the current index reaches the length of the input string, at which point the current substring is added to a vector.
*/

#include<iostream>
#include<vector>
#include<string>
using namespace std ;

void sub_string(string &str,int i , string result,vector<string> &final_substring){
    if(i==str.length()){
        final_substring.push_back(result);
        return;
    }
    sub_string(str,i+1,result + str[i],final_substring);
    sub_string(str,i+1,result ,final_substring);

}
int main(){
    string  str = "abcd";
     vector<string> final_substring ;
     sub_string(str,0," ",final_substring);
     for(int i=0;i<final_substring.size();i++){
        cout<<final_substring[i]<<" ";
     }
}